//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBMS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnBook
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Title { get; set; }
        public string Publication { get; set; }
        public string AuthorName { get; set; }
        public string ISBN { get; set; }
        public string BorrowDate { get; set; }
        public string ReturnDate { get; set; }
    }
}
